In [1]:
import pandas as pd
import numpy as np

In [4]:
data=pd.read_csv(r"C:\Users\sandeep\OneDrive\Desktop\crop-yield-prediction\crop_yield_dataset.csv")
data

    soil_type  rainfall  temperature  fertilizer  area  humidity   yield
0       Sandy     125.8         23.6        13.3  3.92      54.6  1363.0
1       Loamy     174.0         31.7        76.3  0.66      48.7  2181.0
2        Clay      98.0         28.4        69.7  3.86      70.6  1510.0
3       Loamy     184.3         37.9        52.7  1.41      66.3  2143.0
4       Loamy     108.4         36.3        86.0  4.81      51.9  1747.0
..        ...       ...          ...         ...   ...       ...     ...
495     Black     184.5         25.0        26.9  0.61      46.9  2014.0
496      Clay      52.0         32.3        42.0  3.41      55.5   987.0
497     Black      62.8         34.1        80.5  3.37      32.3  1232.0
498     Black      81.2         23.3        59.9  2.03      37.7  1292.0
499     Black      54.0         23.4        10.5  0.82      75.9   915.0

[500 rows x 7 columns]

In [14]:
data.shape

(500, 7)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   soil_type    500 non-null    object
 1   rainfall     500 non-null    float64
 2   temperature  500 non-null    float64
 3   fertilizer   500 non-null    float64
 4   area         500 non-null    float64
 5   humidity     500 non-null    float64
 6   yield        500 non-null    float64
dtypes: float64(6), object(1)
memory usage: 27.5+ KB

In [6]:
data.isna().sum()

soil_type      0
rainfall       0
temperature    0
fertilizer     0
area           0
humidity       0
yield          0
dtype: int64

In [10]:
data['soil_type'].value_counts()

soil_type
Sandy    112
Black    109
Red       95
Loamy     93
Clay      91
Name: count, dtype: int64

### Label encoding

In [12]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data['soil_type']=le.fit_transform(data['soil_type'])

In [13]:
data

     soil_type  rainfall  temperature  fertilizer  area  humidity   yield
0            4     125.8         23.6        13.3  3.92      54.6  1363.0
1            2     174.0         31.7        76.3  0.66      48.7  2181.0
2            1      98.0         28.4        69.7  3.86      70.6  1510.0
3            2     184.3         37.9        52.7  1.41      66.3  2143.0
4            2     108.4         36.3        86.0  4.81      51.9  1747.0
..         ...       ...          ...         ...   ...       ...     ...
495          0     184.5         25.0        26.9  0.61      46.9  2014.0
496          1      52.0         32.3        42.0  3.41      55.5   987.0
497          0      62.8         34.1        80.5  3.37      32.3  1232.0
498          0      81.2         23.3        59.9  2.03      37.7  1292.0
499          0      54.0         23.4        10.5  0.82      75.9   915.0

[500 rows x 7 columns]

In [16]:
X=data.drop('yield',axis=1)
y=data['yield']

In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [21]:
from sklearn.ensemble import RandomForestRegressor
rfr=RandomForestRegressor()
rfr.fit(X_train,y_train)

RandomForestRegressor()

In [22]:
rfr.score(X_test,y_test)

0.94791011282858

In [26]:
import pickle

pickle.dump(rfr, open("model.pkl", "wb"))
pickle.dump(le, open("encoder.pkl", "wb"))

print("Model saved successfully")

Model saved successfully